# Generated by Django 3.2.23 on 2024-03-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='vcl',
            new_name='prod',
        ),
    ]
